CREATE TABLE Respuestas (
  Id INT PRIMARY KEY IDENTITY(1,1),
  Q1 INT NOT NULL,
  Q2 INT NOT NULL,
  Q3 INT NOT NULL,
  Q4 INT NOT NULL,
  Q5 INT NOT NULL,
  Total INT NOT NULL,
  Fecha DATETIME DEFAULT GETDATE()
);